### PR TITLE
Adding sf and stars as inputs

### PR DESCRIPTION
**Pull request by btupper**
This PR adds `sf`/`stars` as inputs to many of the functions. To the user the changes are opaque. Input rasters seem to be transformed into data.frames so really this PR simply expands the wrapper.

I have not tried to add terra (`SpatVector`/`SpatRaster`) to the mix but it feels like it should be doable. 

Is it bad form to consider altering the `ENMevaluation` class such that user chooses sp/Raster*, terra/SpatRaster or sf/stars when accessing predictions?  Perhaps that would be trivial if it had an access method, but it won't work with direct slot access (I don't think).

### CODE REVIEW

**Comment by jamiemkass** [comment]
@btupper Going to finally test this PR, but wondering what as_dataframe is and why you changed from as.data.frame.

**Comment by jamiemkass** [comment]
Okay, I see you added a new "as_dataframe" function to handle the different types, and that's s good idea, but it was failing when some of the inputs were NULL, so working on fixing it. 

I was wondering, is this PR mostly about converting other data types to data frames? If so, why was it necessary to make a new function? Wouldn't it be easier to just convert them in the beginning of ENMevaluate? And perhaps do the same with the plotting functions? I'd prefer something simple like that to making a new as.data.frame function, but that's just my personal preference.

**Comment by btupper** [comment]
Once I waded into the workflow it seemed to me that all data inputs eventually are transformed into data frames with numbered rownames.  The idea of this PR is to leverage that by allowing the workflow to be polymorphic as much as possible. It seems like a single function to manage the many different inputs was a good way to go.  As I set things up, I think `as_dataframe()` is only used internally.  To the user its role is hidden; in fact it may not need to be exported.

It certainly is your call about where to manage polymorphism.  If all users only use `ENMevaluate()` and never interact with any of the other functions then handling it only there would make a great deal of sense.  On the other hand, if the user wanted to interact with, for example, one or more of the partitioning functions before running ENMeval then they would have to think about what form their input data is.

**Comment by jamiemkass** [comment]
I can see both arguments, but you make a good point. For internal purposes, this would be more efficient. But I do worry about tracing errors when developing, and having more internal replacements for basic functions makes that a bit more difficult. 

That said, I do really appreciate the work you've done, as it will help me accommodate other data types. However, I think that I will table this for now when releasing 2.0.4, as it's already done, but when I have time I'll integrate this functionality for the next version. Thanks so much for contributing, and I'll let you know when this stuff is finally functional on the Github version. Until then, your fork will provide a good example of how this works.

**Pull request merged**
